add_newline = true

# ~/.config/starship.toml
format = """
[$directory](fg:6) $hostname $git_branch$git_status$git_commit[$time](fg:7 bold)
$python$character
"""

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[character]
success_symbol = "[>](bold green) "
error_symbol = "[X](bold red) "

[aws]
disabled = true

[directory]
home_symbol = ""
truncation_length = 1
format = "[$path](fg:0 bg:6 bold)[$read_only]($read_only_style)"
read_only = " "
read_only_style = "fg:0 bg:6 bold"

[time]
disabled = false
format = "[$time](fg:0 bg:7 bold)"

[python]
detect_extensions = [".python-version", "Pipfile", "__init__.py", "pyproject.toml", "requirements.txt", "setup.py", "tox.ini"]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[hostname]
ssh_only = true
format = "[](fg:3)[$hostname](fg:0 bg:3 bold)[](fg:3)"
