add_newline = true

# ~/.config/starship.toml
format = """
[$directory](fg:6) $git_branch$git_status$git_commit[$time](fg:15 bold)
$python$character
"""

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[aws]
disabled = true

[directory]
home_symbol = ""
truncation_length = 1
format = "[$path](fg:0 bg:6 bold)[$read_only]($read_only_style)"

[time]
disabled = false
format = "[$time](fg:0 bg:15 bold)"

[python]
detect_extensions = [".python-version", "Pipfile", "__init__.py", "pyproject.toml", "requirements.txt", "setup.py", "tox.ini"]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
